pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main',
                url: 'https://github.com/your-github-username/your-repo.git'
            }
        }

        stage('Build Application') {
            steps {
                echo 'Building application after GitHub push 🚀'
            }
        }
    }

    post {
        success {
            echo 'Webhook triggered Jenkins build successfully ✅'
        }
    }
}