pipeline {
    agent any

    stages {

        stage('Parallel Execution') {

            parallel {

                stage('Frontend Tests') {
                    steps {
                        echo 'Running frontend tests...'
                        sh 'sleep 5'
                    }
                }

                stage('Backend Tests') {
                    steps {
                        echo 'Running backend tests...'
                        sh 'sleep 5'
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying application 🚀'
            }
        }
    }

    post {

        success {
            echo 'Parallel pipeline executed successfully ✅'
        }

        failure {
            echo 'Pipeline failed ❌'
        }
    }
}