pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t my-python-app .'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh 'docker run --name python-container my-python-app'
            }
        }
    }

    post {
        success {
            echo 'Docker container executed successfully ✅'
        }

        always {
            sh 'docker rm -f python-container || true'
        }
    }
}