pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main',
                url: 'https://github.com/your-github-repo-url.git'
            }
        }

        stage('List Project Files') {
            steps {
                sh 'ls -la'
            }
        }

        stage('Run Application') {
            steps {
                sh 'python3 app.py'
            }
        }
    }

    post {
        success {
            echo 'GitHub repository integrated successfully ✅'
        }
    }
}