pipeline {
    agent any

    environment {
        IMAGE_NAME = "demo-app"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip3 install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'python3 test_app.py'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Archive Files') {
            steps {
                sh 'tar -cvf build.tar app.py Dockerfile'
                archiveArtifacts artifacts: 'build.tar'
            }
        }

        stage('Approval') {
            steps {
                input 'Approve deployment?'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker run --rm $IMAGE_NAME'
            }
        }
    }

    post {

        success {
            echo 'CI/CD Pipeline completed successfully ✅'
        }

        failure {
            echo 'Pipeline failed ❌'
        }

        always {
            echo 'Pipeline execution finished'
        }
    }
}