pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/git/git.git'
            }
        }

        stage('List Files') {
            steps {
                sh 'ls -l'
            }
        }
    }

    post {
        success {
            echo 'Repository cloned successfully ✅'
        }
    }
}